Repository taptima/fsd-next-template, pull requests merged in 2024-01, with the labels that each got.

#14 chore: remove branch name validation
  .husky/pre-commit
  .validate-branch-namerc.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#16 feat: setup github actions
  .github/actions/pnpm-install/action.yml
  .github/workflows/checks.yml
Labels: enhancement

#8 chore(FSK-67): update linters dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#9 chore(FSK-67): update patches
  package.json
  pnpm-lock.yaml
Labels: dependencies

#10 chore(FSK-67): update storybook dependencies
  package.json
  pnpm-lock.yaml
  src/entities/Product/ui/ProductsList/index.tsx
  src/pages/ProductsPage/model/services/useGetProductPageProductsSWR.test.ts
  src/shared/config/project/createStore/index.ts
  src/shared/lib/api/GraphQL/index.ts
  src/shared/lib/helpers/initializeDevtoolsOptions/initializeDevtoolsOptions.test.ts
Labels: dependencies

#11 chore(FSK-67): update minor dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies

#15 refactor: modify exception handling 'console.groupCollapsed'
  src/shared/config/project/logger/index.ts
Labels: enhancement

#20 build(deps): update next to 14.1.0
  package.json
  patches/next@13.5.2.patch
  patches/next@14.1.0.patch
  pnpm-lock.yaml
  src/app/@types/global.d.ts
  src/shared/types/utils.ts
Labels: dependencies

#21 build: update all deps
  .commitlintrc.yml
  package.json
  pnpm-lock.yaml
Labels: dependencies

#22 chore: update sassOptions for storybook purposes
  next.config.js
Labels: bug
